version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-teste-tokenlab
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: calendar
    ports:
      - "3306:3306"